add_executable(market_data_example market_data_example.cpp)
target_link_libraries(market_data_example PRIVATE bintrade::bintrade)

add_executable(place_order_example place_order_example.cpp)
target_link_libraries(place_order_example PRIVATE bintrade::bintrade)

add_executable(websocket_stream_example websocket_stream_example.cpp)
target_link_libraries(websocket_stream_example PRIVATE bintrade::bintrade)
